"""create password reset token

Revision ID: 29398c0bf2d1
Revises: e817f2b437fa
Create Date: 2023-06-25 14:23:51.742726

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "29398c0bf2d1"
down_revision = "e817f2b437fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passwordresettoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("is_invalidated", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value"),
    )
    op.create_index(op.f("ix_passwordresettoken_id"), "passwordresettoken", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_passwordresettoken_id"), table_name="passwordresettoken")
    op.drop_table("passwordresettoken")
    # ### end Alembic commands ###
