"""add slug field to event-related models

Revision ID: 9d4d6dfb8f75
Revises: 3f57872ff230
Create Date: 2023-08-06 16:35:06.629968

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9d4d6dfb8f75"
down_revision = "3f57872ff230"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artist", sa.Column("slug", sa.String(), nullable=False))
    op.create_index(op.f("ix_artist_slug"), "artist", ["slug"], unique=True)
    op.add_column("event", sa.Column("slug", sa.String(), nullable=False))
    op.create_index(op.f("ix_event_slug"), "event", ["slug"], unique=True)
    op.add_column("eventtype", sa.Column("slug", sa.String(), nullable=False))
    op.create_index(op.f("ix_eventtype_slug"), "eventtype", ["slug"], unique=True)
    op.add_column("location", sa.Column("slug", sa.String(), nullable=False))
    op.create_index(op.f("ix_location_slug"), "location", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_slug"), table_name="location")
    op.drop_column("location", "slug")
    op.drop_index(op.f("ix_eventtype_slug"), table_name="eventtype")
    op.drop_column("eventtype", "slug")
    op.drop_index(op.f("ix_event_slug"), table_name="event")
    op.drop_column("event", "slug")
    op.drop_index(op.f("ix_artist_slug"), table_name="artist")
    op.drop_column("artist", "slug")
    # ### end Alembic commands ###
