"""create event-related models

Revision ID: 0c00b6b3297c
Revises: 29398c0bf2d1
Create Date: 2023-08-04 17:44:26.060026

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c00b6b3297c"
down_revision = "29398c0bf2d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("photo", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artist_id"), "artist", ["id"], unique=False)
    op.create_index(op.f("ix_artist_name"), "artist", ["name"], unique=False)
    op.create_table(
        "eventtype",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_type_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_type_id"],
            ["eventtype.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eventtype_id"), "eventtype", ["id"], unique=False)
    op.create_index(op.f("ix_eventtype_name"), "eventtype", ["name"], unique=False)
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=40), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_location_city"), "location", ["city"], unique=False)
    op.create_index(op.f("ix_location_id"), "location", ["id"], unique=False)
    op.create_index(op.f("ix_location_name"), "location", ["name"], unique=False)
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("poster_vertical", sa.String(), nullable=True),
        sa.Column("poster_horizontal", sa.String(), nullable=True),
        sa.Column("organizer", sa.String(length=128), nullable=False),
        sa.Column("held_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["eventtype.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_id"), "event", ["id"], unique=False)
    op.create_index(op.f("ix_event_name"), "event", ["name"], unique=False)
    op.create_table(
        "event_artist",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "artist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_artist")
    op.drop_index(op.f("ix_event_name"), table_name="event")
    op.drop_index(op.f("ix_event_id"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_location_name"), table_name="location")
    op.drop_index(op.f("ix_location_id"), table_name="location")
    op.drop_index(op.f("ix_location_city"), table_name="location")
    op.drop_table("location")
    op.drop_index(op.f("ix_eventtype_name"), table_name="eventtype")
    op.drop_index(op.f("ix_eventtype_id"), table_name="eventtype")
    op.drop_table("eventtype")
    op.drop_index(op.f("ix_artist_name"), table_name="artist")
    op.drop_index(op.f("ix_artist_id"), table_name="artist")
    op.drop_table("artist")
    # ### end Alembic commands ###
