"""create organizer model

Revision ID: 3f57872ff230
Revises: 0c00b6b3297c
Create Date: 2023-08-06 12:59:33.828933

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3f57872ff230"
down_revision = "0c00b6b3297c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizer_id"), "organizer", ["id"], unique=False)
    op.create_index(op.f("ix_organizer_name"), "organizer", ["name"], unique=True)
    op.add_column("event", sa.Column("organizer_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_organizer_id", "event", "organizer", ["organizer_id"], ["id"])
    op.drop_column("event", "organizer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("organizer", sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint("fk_organizer_id", "event", type_="foreignkey")
    op.drop_column("event", "organizer_id")
    op.drop_index(op.f("ix_organizer_name"), table_name="organizer")
    op.drop_index(op.f("ix_organizer_id"), table_name="organizer")
    op.drop_table("organizer")
    # ### end Alembic commands ###
