"""add missing constraints

Revision ID: f91924d53bf8
Revises: 9d4d6dfb8f75
Create Date: 2023-08-08 18:38:25.476873

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f91924d53bf8"
down_revision = "9d4d6dfb8f75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("event", "organizer_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("event", "created_by_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("event", "event_type_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("event", "location_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("passwordresettoken", "is_invalidated", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("passwordresettoken", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_passwordresettoken_value"), "passwordresettoken", ["value"], unique=True)
    op.alter_column("user", "is_activated", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_disabled", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_disabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "is_activated", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_passwordresettoken_value"), table_name="passwordresettoken")
    op.alter_column("passwordresettoken", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("passwordresettoken", "is_invalidated", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("event", "location_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("event", "event_type_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("event", "created_by_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("event", "organizer_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
