"""create ticket models

Revision ID: 8ef5d44c6c71
Revises: f91924d53bf8
Create Date: 2023-08-31 17:16:54.927908

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ef5d44c6c71"
down_revision = "f91924d53bf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticketcategory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quota", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticketcategory_id"), "ticketcategory", ["id"], unique=False)
    op.create_index(op.f("ix_ticketcategory_name"), "ticketcategory", ["name"], unique=True)
    op.create_table(
        "ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticket_category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_category_id"],
            ["ticketcategory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_ticket_email"), "ticket", ["email"], unique=False)
    op.create_index(op.f("ix_ticket_id"), "ticket", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_id"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_email"), table_name="ticket")
    op.drop_table("ticket")
    op.drop_index(op.f("ix_ticketcategory_name"), table_name="ticketcategory")
    op.drop_index(op.f("ix_ticketcategory_id"), table_name="ticketcategory")
    op.drop_table("ticketcategory")
    # ### end Alembic commands ###
