"""remove index from ticket category name

Revision ID: 7ba4a157a11f
Revises: 895ca892d8e7
Create Date: 2024-01-18 21:31:35.937752

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ba4a157a11f"
down_revision = "895ca892d8e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ticketcategory_name", table_name="ticketcategory")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_ticketcategory_name", "ticketcategory", ["name"], unique=False)
    # ### end Alembic commands ###
